name: flutter_templete
description: "A new Flutter project that uses riverpod as state management."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: "3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # state
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2

  # look and feel
  flutter_svg: ^2.0.17
  top_snackbar_flutter: ^3.2.0
  country_code_helper: ^0.2.0
  flex_color_scheme: ^8.1.1

  # network and serilization
  http: ^1.3.0
  freezed_annotation: 2.4.1
  json_annotation: ^4.9.0

  # utils and services
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  path: ^1.9.1
  intl: 0.19.0

  # firebase
  # firebase_core: ^3.12.1
  # firebase_analytics: ^11.4.4
  # firebase_crashlytics: ^4.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: 2.4.13
  freezed: 2.4.8
  json_serializable: 6.9.0
  # dart run flutter_native_splash:create
  flutter_native_splash: ^2.4.5
  # dart run flutter_launcher_icons:generate
  flutter_launcher_icons: ^0.14.3
  flutter_asset_generator: ^1.2.0

flutter_native_splash:
  color: "#FFFFFF"
  android_12:
    color: "#FFFFFF"

flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/logo/fgi.png"
  image_path_ios: "assets/logo/foreground_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo/fgi.png"

flutter_asset_generator:
  output: lib/generated/assets.gen.dart
  name: Assets
  replace:
    - from: “
      to:
    - from: ”
      to:
    - from: ’
      to:
    - from: (
      to:
    - from: )
      to:
    - from: "!"
      to:
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logo/
    - assets/icons/
    - assets/dumbs/

  # To add custom fonts to your application, add a fonts section here, // TODO : add custom fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
